### ISSUE TITLE
The code is very confusing and there are a lot of duplicates in there

### ISSUE THREAD

**Issue by gerd2002** [gerd2002/Uselessbot#3]
Beautifying the code is going to be hard, but necessary. I will try to do that by myself.

**Comment by Sanduhr32** [comment]
Yup because you have an outdated version

**Comment by gerd2002** [comment]
Then push the newer one, damn!

**Comment by Sanduhr32** [comment]
I cant. If i could i would do it instantly

**Comment by gerd2002** [comment]
The issue is not closed yet!

**Comment by gerd2002** [comment]
Just push your version to your repo and merge my pull request
